server:
  port: 8864
dubbo:
  # 配置服务信息
  application:
    name: dubbo-c50
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://127.0.0.1:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20864
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: Abc123
    listener:
      simple:
        #自动签收auto  手动 manual
        acknowledge-mode: manual
posturl: http://127.0.0.1:8911/api/hf/order/submit
searchurl: http://127.0.0.1:8911/api/order/query
order:
   log:
      queue: order.queue.orderflow
   search:
      queue:
         exchange: amq.direct
         post: asyn.pay.yxy.post.search
         delay: asyn.pay.yxy.post.search.delay
         
         
