server:
  port: 8868
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  main:
    allow-bean-definition-overriding: true
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/assign_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
    password: ENC(4Cc5xbhL1jiI/zpaGH4aumSB36bw/dNSx5mLen0fK2ZxcQyXBxKsDflz9lJjF+al)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #初始化连接数
    initialSize: 100
    #最大连接数
    maxActive: 200
    #最小连接数
    minIdle: 50
    #配置获取连接等待超时的时间
    maxWait: 10000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(4Cc5xbhL1jiI/zpaGH4aumSB36bw/dNSx5mLen0fK2ZxcQyXBxKsDflz9lJjF+al)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    show-sql: false
    # 自动生成表结构
    generate-ddl: false
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  # Elasticsearch
  data:
    elasticsearch:
      client:
        reactive:
          # 要连接的ES客户端 多个逗号分隔
          endpoints: 127.0.0.1:9300
      # 未使用到ES 关闭其持久化存储
      repositories:
        enabled: false
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            misfireThreshold: 100
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  boot:
    api:
      # 修改上下文路径
      context-path: /api/api
      client:
        url: http://127.0.0.1:${server.port}/api/api
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: Abc123
    listener:
      simple:
        #自动签收auto  手动 manual
        acknowledge-mode: manual
# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: xboot
api:
  #获取运营商服务url
  getServiceNameUrl: http://127.0.0.1:58080/getInfo
  #api版本
  version: 0.0.1
  # 全局限流
  ratelimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制200个请求
    limit: 200
  # IP限流
  iplimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制20个请求
    limit: 20
  # token交互方式
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  qqlbs:
    key: 你的腾讯位置服务key
# 忽略鉴权url
ignored:
  urls:
    - /api/oauth2/**
    - /api/actuator/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /api/memberUsers
    - /api/test/**
    - /api/**
# Actuator
management:
  health:
    # 暂未用到ES 关闭其健康检查
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
  endpoints:
    web:
      base-path: /api/actuator/
      exposure:
        include: '*'

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志
logging:
  # 输出级别
  level:
    root: info
  #file:
    # 指定路径
    #path: api-logs
    # 最大保存天数
    #max-history: 7
    # 每个文件最大大小
    #max-size: 5MB
fdfs:
  tracker-list: 127.0.0.1:22122
  web-server-url: http://127.0.0.1:9080
  connect-timeout: 6000

dubbo:
  # 配置服务信息
  application:
    name: dubbo-api
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://127.0.0.1:8848
  # 设置超时时间
  consumer:
    timeout: 10000
    retries: -1
    
order:
   log:
      queue: order.queue.orderflow
   search:
      queue:
         exchange: amq.direct
         post: asyn.pay.yxy.post.search
         delay: asyn.pay.yxy.post.search.delay
   account:
      queue: asyn.order.account.queue
   notify:
      queue: asyn.order.notify.queue
      delay: asyn.order.notify.queue.delay
   send:
      queue: asyn.order.send.queue
         

